
#!/usr/bin/env Rscript

#################################### GaussClust.R ########################################

############ CONDUCT SETUP, READ IN AND PLOT THE DATA
setwd('/Users/justinbagley/Documents/GitHub/GaussClust/examples')
# 
##--Load needed library, R code, or package stuff. Install packages if not present.
packages <- c('bgmm', 'Rmixmod', 'StatMatch', 'MASS', 'ggfortify', 'labdsv')
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
    install.packages(setdiff(packages, rownames(installed.packages())))
}

library(bgmm)
library(Rmixmod)
library(StatMatch)
library(MASS)
library(ggfortify)
library(labdsv)

##--Read in the data:
mydata_names <- read.table('./Enyalius_35.txt', h=T)
str(mydata_names)
mydata <- mydata_names[,-c(1:3)]
str(mydata)

##--Graph of pairwise data plots when there are small numbers of characters (else basic R 
##--function and windows cannot handle the plots resulting from calling 'plot' function):
if( dim(mydata_names)[2] < 10 ){
print('Making pairwise plots of the data... ')
pdf('pairwise_data_plots.pdf')
plot(mydata_names)
dev.off()} else {print('Cannot do pairwise plots of the data (too much data)... ')
}


############ ANALYSIS

############ I. SCALE / STANDARDIZE DATA USING NMDS 
##--Estimate Gower distances from the original morphological data matrix w/o names: 
mydata_gower <- gower.dist(mydata)

##--Use ggfortify to visualize the gower distnces:
pdf('gower_dist_gg_autoplot.pdf')
autoplot(mydata_gower)
dev.off()

##--Conduct NMDS using simple 'nmds' function from labdsv pkg, RETAINING k DIMENSIONS,
##--with the goal being to get NMDS points for use downstream in Rmixmod and/or bgmm:
mydata_gower_nmds <- nmds(mydata_gower, k=4)
pdf('gower_nmds_plot.pdf')
plot(mydata_gower_nmds)
dev.off()

##--Use ggfortify to visualize the NMDS:
pdf('gower_gg_nmds_plot.pdf')
autoplot(isoMDS(mydata_gower, k=4), colour = 'orange', size = 1, shape = 3)
dev.off()

##--Save each dimension of values retained from NMDS into a separate variable, and then
##--in a data frame (extension 'df'):
nmds_1 <- mydata_gower_nmds$points[,1]
nmds_2 <- mydata_gower_nmds$points[,2]
nmds_3 <- mydata_gower_nmds$points[,3]
nmds_4 <- mydata_gower_nmds$points[,4]
nmds_dims_df = data.frame(nmds_1, nmds_2, nmds_3, nmds_4)


############ II. PREP AND CHECK DATA FOR GMM ANALYSES
##--Make data frame containing the individual sample names as well as columns of points
##--from NMDS dimensions retained during STEP I above. Also save the new data frame(s) to
##--file(s) in the working dir; we may want it handy in case we need it later...
sample_names <- mydata_names[,1]
type <- mydata_names[,2]
species <- mydata_names[,3]
mydata_names_df <- data.frame(sample_names, type, species, nmds_1, nmds_2, nmds_3, nmds_4)
write.table(mydata_names_df, file='mydata_names_df.txt')

##--Subset the NMDS points by 'known' and 'unknown' individuals, for bgmm. Also write the
##--resulting new data frames back to file in working dir--in case of subsequent checks: 
attach(mydata_names_df)
known_0 <- mydata_names_df[ which(mydata_names_df$type=='known'), ]
detach(mydata_names_df)
row.names(known_0) <- known_0[,1]
known_0
write.table(known_0, file='known_0.txt')
str(known_0)
#
knowns <- known_0[,-c(1:3)]
knowns
dim(knowns)[1]
write.table(knowns, file='knowns.txt')
str(knowns)
#
known_labels <- subset(mydata_names_df$species, type=='known')
length(known_labels)
known_labels
#
attach(mydata_names_df)
unknown_0 <- mydata_names_df[ which(mydata_names_df$type=='unknown'), ]
detach(mydata_names_df)
row.names(unknown_0) <- unknown_0[,1]
unknown_0 <- unknown_0[,-c(1:3)]
write.table(unknown_0, file='unknown_0.txt')
str(unknown_0)
#
unknown_labels <- subset(mydata_names_df$species, type=='unknown')
length(unknown_labels)
unknown_labels

##--Remove names from data frame of unknowns and place in var 'X' (bgmm unknowns var). Also 
##--read in the belief matrix (B) containing prior probabilities for the knowns, with 0.95 
##--probability for 'known' labeled individuals and all other cells receiving probs of
##--0.05/k (where k is number of components or clusters, and number of columns in B). 
##--***IMPORTANT***: matrix B is generated by the user prior to running this script and
##--ONLY contains individuals classified as 'knowns'.
row.names(unknown_0) <- c(1:dim(unknown_0)[1])
unknowns <- unknown_0
X <- unknowns
X
dim(X)
#
B <- read.table('./probs_35.txt', header=TRUE, sep='	')
names(B) <- c(0:2)
row.names(B) <- B[,1]
B <- B[,-c(1)]
B
dim(B)
#
##--What about arbitrary beliefs on knowns?
##--This is commented out for now; however, the following lines of code allow the user to 
##--make a couple of arbitrary belief matrices, to analyze and compare with the belief-
##--based GMMs in bgmm, if called by the user using the -b flag. Uncomment here and under
##--Section V below if desired.
# p1=0.95
# B2 <- (matrix(p1, nrow = dim(B)[1], ncol = 2))
# row.names(B2) <- row.names(knowns)
# p2=0.066666666666667
# B3 <- (matrix(p2, nrow = dim(B)[1], ncol = 2))
# row.names(B3) <- row.names(knowns)



############ III. CONDUCT UNSUPERVISED GMM CLUSTERING ANALYSIS IN RMIXMOD
if( 1 == '0' ){print('Skipping unsupervised GMM analysis... ')} else {if(1 == '1' ){
date()
print('Conducting unsupervised GMM analysis of the data using Rmixmod... ')
mydata_gower_gmm <-mixmodCluster(nmds_dims_df, nbCluster=1:5)
summary(mydata_gower_gmm)
pdf('gower_gmm_result.pdf')  ## SAVE THESE PLOTS--THEY'RE AWESOME!!!
plot(mydata_gower_gmm)
plot(mydata_gower_gmm, c(1, 2))
plot(mydata_gower_gmm, c(1, 3))
plot(mydata_gower_gmm, c(1, 4))
plot(mydata_gower_gmm, c(2, 3))
plot(mydata_gower_gmm, c(2, 4))
plot(mydata_gower_gmm, c(3, 4))
dev.off()
mydata_gower_gmm['partition']} else { print('WARNING: Something went wrong deciding whether or not to call unsupervised GMM analysis... ')
	}
}


####### IV. (SEMI-)SUPERVISED GMM-BASED DISCRIMINANT ANALYSIS IN RMIXMOD:
if( 1 == '0' ){print('Skipping GMM-based discriminant analysis in Rmixmod... ')} else {if(1 == '1' ){
## Analysis:
##    A. Learning:
mydata_known_learn <- mixmodLearn(as.data.frame(knowns), as.factor(known_labels), nbCVBlocks = 10)
mydata_known_learn['bestResult']
graphics.off()
quartz()
pdf('superRmixmod_learn_results.pdf')   ## SAVE THESE PLOTS--THEY'RE AWESOME!!!
plot(mydata_known_learn)
plot(mydata_known_learn, c(1, 2))
plot(mydata_known_learn, c(1, 3))
plot(mydata_known_learn, c(1, 4))
plot(mydata_known_learn, c(2, 3))
plot(mydata_known_learn, c(2, 4))
plot(mydata_known_learn, c(3, 4))
dev.off()
#
##    B. Prediction:
## My prior experience with this (supervised prediction on lizard morphological dataset)
## suggests that prediction success when going from a set of knowns (1:1 or partial coverage)
## to unknowns is usually not so good (~20%). Nevertheless, here goes:
mydata_unknown_prediction <- mixmodPredict(data = X, classificationRule = mydata_known_learn['bestResult'])
summary(mydata_unknown_prediction)
mean(as.integer(unknown_labels) == mydata_unknown_prediction['partition'])
	}
}

####### V. (SEMI-)SUPERVISED BELIEF-BASED GMM ANALYSIS IN BGMM:
if( 3 == '0' ){print('Skipping belief-based GMM analysis in bgmm... ')} else if(3 == '1' ){
supervisedModel <- supervised(as.data.frame(knowns), class = as.factor(known_labels))
supervisedModel
# pdf('bgmm_supervised_result.pdf')
# plot(supervisedModel)
# dev.off()
} else if(3 == '2' ){
semisupervisedModel <- semisupervised(as.data.frame(X), as.data.frame(knowns), class = as.factor(known_labels), k = 2, P = B)

pdf('bgmm_semisupervised_result.pdf')
plot(semisupervisedModel)
dev.off()
z <- as.data.frame(semisupervisedModel$tij)
write.table(z, file='bgmm_semisupervised_posteriorProbs.txt', sep='	')} else if(3 == '3' ){
supervisedModel <- supervised(as.data.frame(knowns), class = as.factor(known_labels))
supervisedModel
# pdf('bgmm_supervised_result.pdf')
# plot(supervisedModel)
# dev.off()
semisupervisedModel <- semisupervised(as.data.frame(X), as.data.frame(knowns), class = as.factor(known_labels), k = 2, P = B)

pdf('bgmm_semisupervised_result.pdf')
plot(semisupervisedModel)
dev.off()
z <- as.data.frame(semisupervisedModel$tij)
write.table(z, file='bgmm_semisupervised_posteriorProbs.txt', sep='	')} else {print('Sorry, the belief, soft, and unsupervised routines in bgmm are not yet supported in GaussClust... ')}




##--What about arbitrary beliefs on knowns?
# modelSoft1 <- soft(X, knowns, class = as.factor(known_labels), k = 2, P = B2)
# pdf('bgmm_modelSoft1_result.pdf')  ## SAVE THIS PLOT!
# plot(modelSoft1)
# dev.off()
#
# modelSoft2 <- soft(X, knowns, class = as.factor(known_labels), k = 2, P = B3)
# pdf('bgmm_modelSoft2_result.pdf')  ## SAVE THIS PLOT!
# plot(modelSoft2)
# dev.off()
#
# quartz()
# pdf('bgmm_modelSoft1_vs_modelSoft2_2x1.pdf')  ## SAVE THIS PLOT!
# par(mfrow=c(2,1))
# plot(modelSoft1)
# plot(modelSoft2)
# dev.off()






######################################### END ############################################

